Update buildspec-apply.yml

diff --git a/buildspec-apply.yml b/buildspec-apply.yml
--- a/buildspec-apply.yml
+++ b/buildspec-apply.yml
@@ -18,17 +18,19 @@ phases:
     commands:
       - echo "Initializing Terraform"
       - terraform init -input=false
+      - terraform state list
 
   build:
     commands:
-      - echo "Applying previously generated Terraform plan"
-      - terraform apply
-        -input=false
-        -lock-timeout=5m
-        -auto-approve
-        tfplan
+      - echo "Destroying Terraform infrastructure"
+      - terraform destroy -input=false -lock-timeout=5m -auto-approve
 
   post_build:
     commands:
-      - terraform output
-      - echo "Terraform apply completed"
+      - |
+        if [ "$CODEBUILD_BUILD_SUCCEEDING" = "1" ]; then
+          echo "Terraform destroy completed successfully"
+        else
+          echo "Terraform destroy failed"
+          exit 1
+        fi
